# Generated by Django 5.0.14 on 2025-05-28 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
            },
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tick',
                'verbose_name_plural': 'Ticks',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='TickTable',
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['name'], name='ticktable_s_name_6a4ff1_idx'),
        ),
        migrations.AddField(
            model_name='tick',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ticktable.script'),
        ),
        migrations.AddIndex(
            model_name='tick',
            index=models.Index(fields=['timestamp'], name='ticktable_t_timesta_420907_idx'),
        ),
    ]
