# Generated by Django 5.0.14 on 2025-06-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktable', '0002_script_tick_delete_ticktable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='best_ask_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='best_ask_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='best_bid_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='best_bid_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='event_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='first_trade_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='first_trade_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='last_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='last_trade_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='price_change',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='price_change_percent',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='statistics_close_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='statistics_open_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='total_traded_base_volume',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='total_traded_quote_volume',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='total_trades',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='weighted_avg_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
    ]
